name: Push Images to Aliyun ACR

on:
  push:
    paths:
      - 'images_cybergym_subset.txt'
  workflow_dispatch:

jobs:
  push-to-acr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # - name: Free Disk Space
      #   uses: jlumbroso/free-disk-space@main
      #   with:
      #     tool-cache: true
      #     docker-images: false # 这里设为false，因为我们要拉取新镜像

      # 1. 登录阿里云镜像仓库
      # - name: Login to ACR
      #   uses: aliyun/acr-login@v1
      #   with:
      #     login-server: crpi-qb9v9pmucg1slgus.cn-beijing.personal.cr.aliyuncs.com # 根据你的地域修改，如 cn-shanghai
      #     access-key-id: ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_ID }}
      #     access-key-secret: ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_SECRET }}
      #     region-id: cn-beijing  # <--- 必须和上面一致
      - name: Login to ACR (Standard Mode)
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login --username=nick1845593624 --password-stdin crpi-qb9v9pmucg1slgus.cn-beijing.personal.cr.aliyuncs.com
          
          
      # 2. 构建并推送
      - name: Pull, Tag, and Push
        run: |
          # 变量统统使用那个长地址
          REGISTRY=crpi-qb9v9pmucg1slgus.cn-beijing.personal.cr.aliyuncs.com
          NAMESPACE=github_action1
          
          echo "Starting process..."
          
          # 提取 1 到 56 行进行测试
          sed -n '1,56p' images_mini.txt | while IFS= read -r image || [ -n "$image" ]; do
            [[ -z "$image" || "$image" =~ ^# ]] && continue
            image=$(echo "$image" | xargs)
            
            # 简化命名逻辑：将所有斜杠换成单横杠，且确保没有双横杠
            # 例如 mswebench/catchorg_m_catch2 -> mswebench-catchorg-m-catch2
            RAW_NAME=$(echo "$image" | cut -d':' -f1)
            SAFE_NAME=$(echo "$RAW_NAME" | sed 's/[\/]/--/g' | sed 's/--/-/g')
            TAG=$(echo "$image" | cut -d':' -f2)
            [ "$TAG" == "$image" ] && TAG=latest

            NEW_IMAGE="$REGISTRY/$NAMESPACE/$SAFE_NAME:$TAG"
            
            echo "------------------------------------------------"
            echo "Target Image: $NEW_IMAGE"
            
            if docker pull "$image"; then
              docker tag "$image" "$NEW_IMAGE"
              # 如果这一步报错，说明仓库没创建或命名不规范
              docker push "$NEW_IMAGE"
              docker rmi "$image" "$NEW_IMAGE"
            else
              echo "Failed to pull $image"
            fi
          done


      - name: Check Final Space
        run: df -h
