name: Bulk Download from File

on:
  push:
    paths:
      - 'images_mini.txt'  # 只要你修改这个文件并推送，就自动运行
  workflow_dispatch:   # 也保留手动触发按钮

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Pull and Save
        run: |
          mkdir -p ./docker_images
          while IFS= read -r image || [ -n "$image" ]; do
            [[ -z "$image" || "$image" =~ ^# ]] && continue
            image=$(echo "$image" | xargs)
            
            echo "Processing $image..."
            docker pull "$image"
            CLEAN_NAME=$(echo "$image" | sed 's/[\/:]/_/g')
            docker save -o "./docker_images/${CLEAN_NAME}.tar" "$image"
          done < images_mini.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: all-images
          path: ./docker_images/
